#pragma config(Motor,  port2,           FL,            tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           FR,            tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           BL,            tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           BR,            tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           CL,            tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           CCL,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           UP,            tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
LR
23F
45B
LR//why:
++F
--B
p6+//pl
p7-//pl
p8-//up
Ch1 EAST+
Ch2 NORTH+
Ch3 NORTH+
Ch4 EAST+
*/
void lt(int speed){
  motor[port2] = speed;
  motor[port4] = -speed;
  int ltat = speed;
}
void rt(int speed){
  motor[port3] = speed;
  motor[port5] = -speed;
  int rtat = speed;
}
task main() {
  while (1 == 1){
    if (vexRT[Ch2] == 0){//point turns, positive is clockwise
      lt(vexRT[Ch1]);//east||north
      rt(-vexRT[Ch1]);//west||south
    }else {//differential
      lt(vexRT[Ch2] + vexRT[Ch1]);//north + east
      rt(vexRT[Ch2] - vexRT[Ch1]);//north - east
    }
    if (vexRT[Btn6U] == 1 ){//auto tip-tread toggle
      int at = 1;
    }if (vexRT[Btn6D] == 1 ){
      int at = 0;
    }
    if (int at != 1){//only execute manual control if toggle is off
      if (vexRT[Btn5U] == 1){
        motor[port8] = -127;
      }else if (vexRT[Btn5D] == 1){
        motor[port8] = 127;
      }else {
        motor[port8] = 0;
      }
    }
    if (at == 1 && ltat >= 100 && rtat >= 100){//control direction of auto tread
      motor[port8] = 127;
    }
    if (at == 1 && ltat <= -100 && rtat <= -100){
      motor[port8] = -127;
    }
  }
}
