#pragma config(Motor,  port2,           FL,            tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           FR,            tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           BL,            tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           BR,            tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           CL,            tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           CCL,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           UP,            tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
  while (1 == 1){
    //base
    float powerfactor;
    powerfactor=vexRT[Ch2] / 127;
    motor[port2] = floor(powerfactor * vexRT[Ch1]) + vexRT[Ch4];
    motor[port4] = floor(powerfactor * vexRT[Ch1]) + vexRT[Ch4];
    motor[port3] = floor(-powerfactor * vexRT[Ch1]) - vexRT[Ch4];
    motor[port5] = floor(-powerfactor * vexRT[Ch1]) - vexRT[Ch4];
    //pull
    if (vexRT[Btn6U] == 1){
      motor[port6] = 127;
      motor[port7] = -127;
    }else if (vexRT[Btn6D] == 1){
      motor[port6] = -127;
      motor[port7] = 127;
    }else {
      motor[port6] = 0;
      motor[port7] = 0;
    }
    //up
    if (vexRT[Btn5U] == 1){
      motor[port8] = 127;
    }else if (vexRT[Btn5D] == 1){
      motor[port8] = -127;
    }else {
      motor[port8] = 0;
    }
    motor[port2] = 127;
  }
}
